[package]
name = "blang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.5"
cranelift = "0.97.1"
cranelift-codegen = "0.97.1"
cranelift-module = "0.97.1"
cranelift-native = "0.97.1"
cranelift-object = "0.97.1"
env_logger = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.19"
regex = "1.8.4"
target-lexicon = "0.12.8"
