# Enable debug logs.
export RUST_LOG=trace

# Enable stack traces.
export RUST_BACKTRACE=full

# Run tests.
.PHONY: test
test:
	cargo llvm-cov -- --nocapture

# Generate docs.
.PHONY: docs
docs:
	cargo doc

# Automatically fix lint errors.
.PHONY: fix
fix:
	cargo fix --allow-dirty --allow-staged

# Build and run .bl source code.
.PHONY: %
%:
	cargo run -- build -o out.ll --unoptimized $@.bl

# Inspect the object file generated by the compiler.
.PHONY: inspect
inspect:
	llvm-objdump -d out

# Creates an executable from the source code in "source.bl".
.PHONY: exec
exec: source
	llc -filetype=obj out.ll -o out.o && clang out.o -o out
