name: Build and Push Image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64 ]
    steps:
      - name: Checkout Blang Playground
        uses: actions/checkout@v4
        with:
          repository: bfbachmann/blang-playground
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: compiler/base
          push: true
          tags: bfbachmann/blang-playground:latest
